version: "3.9"

services:
  web:
    build:
      context: .
    command: ["make", "django-start"]
    ports:
      - "8000:8000"
    env_file: ./proninteam_backend/.env
    volumes:
      - ./proninteam_backend:/app/proninteam_backend
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    command: ["make", "celery-start"]
    env_file: ./proninteam_backend/.env
    volumes:
      - ./proninteam_backend:/app/proninteam_backend
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres
    env_file: ./proninteam_backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
