# Generated by Django 5.2 on 2025-04-23 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_collection_author_alter_collection_cause_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["-due_date"],
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-date"],
                "verbose_name": "Донат",
                "verbose_name_plural": "Донаты",
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)),
                name="target_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="amount_positive"
            ),
        ),
    ]
