# Generated by Django 5.2 on 2025-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_collection_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время доната'),
        ),
    ]
