# Generated by Django 5.2 on 2025-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_collection_due_date_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Обложка'),
        ),
    ]
